loc: 
  portal:
    en:               
      target: 'You are trying to access'
      access1: 'To access this website, you must use a'
      access2:  '(WCA) account. Clicking on "Sign in through WCA" will redirect you to the WCA website to confirm that you authorize(d) MyComp to acces your personal data.'
      privacy: 'By signing in to MyComp, you agree to the use of cookies. All our cookies are used for functional purposes only. Please read our privacy policy'
      here: 'here'
      signin: 'Sign in through WCA'
      role: 'I am an organizer or Delegate and I wish to handle my competitions'
    fr:
      target: "Vous essayez d'accéder à"
      access1: 'Pour accéder à ce site, vous devez utiliser un compte'
      access2: '(WCA). Cliquer sur « Se connecter avec la WCA » vous redirigera vers le site web de la WCA pour confirmer que vous autorisez/avez autorisé MyComp à accéder à vos données personnelles.'
      privacy: 'En vous connectant à MyComp, vous acceptez l’utilisation de cookies. Tous nos cookies sont utilisés à des fins fonctionnelles uniquement. Veuillez lire notre politique de confidentialité'
      here: 'ici'
      signin: 'Se connecter avec la WCA'
      role: 'Je suis un organisateur ou un Délégué et je souhaite gérer mes compétitions'