<?php

  require_once dirname( __DIR__, 3 ) . '/config/config-db.php';
  require_once 'orders-functions.php';
  
  
  /** 
   * get_user_imported_competitions(): retrieve all competitions stored in database for which user is a competitor or an organizer/delegate
   * @param (int) user_id: ID of the user to retrieve competitions for
   * @param (mysqli) mysqli: database connection object
   * @return (array) all the imported competitions as an associative array and the error generated by the function
   */

  function get_user_imported_competitions( $user_id, $mysqli )
  {
    $base_request = "competitors LIKE '%[{$user_id}]%' AND  competition_catalog != ''";

    if ( $_SESSION['manageable_competitions'] )
    {
      $competition_ids = "('" . implode( "', '", array_keys( $_SESSION['manageable_competitions'] ) ) . "')";
      $sql = "SELECT * FROM ". DB_PREFIX_CU . "_Main WHERE competition_id IN {$competition_ids} OR ({$base_request});";
    }
    else
    { 
      $sql =  "SELECT * FROM ". DB_PREFIX_CU . "_Main WHERE {$base_request};";
    }

    $query_results = $mysqli->query( $sql );
    
    $user_imported_competitions = [];

    if( $query_results )
    {
      while( $result_row = $query_results->fetch_assoc() )
      { 
        [ $error, $user_order ] = get_user_order( $result_row['competition_id'], $user_id, $mysqli );
        $result_row['has_ordered'] = $error ? null : (! is_null( $user_order ));
        $user_imported_competitions[ $result_row['competition_id'] ] = $result_row;
      }
    }
    else
    {
      $error = mysqli_error( $mysqli );
    }

    return [ $user_imported_competitions, $error ];
  }

?>